name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR Verify - CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0

      - name: Test .Net Core App
        run: dotnet test --no-build

      - name: Formatting Code
        run: dotnet format 
        
      - name: Dotnet Publish
        run: dotnet publish ContactsManager.Web/ContactsManager.Web.csproj --configuration release --no-restore --output artifacts

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ContactsManager Artifact
          path: artifacts
          
  deploy_dev:
    - name: Deploy Dev
      needs: build
      uses: ./.github/workflows/steps-deploy.yml
      with:
        env: dev
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        app_service_name: ${{ env.app_service_name }}
        
  deploy_prod:
    - name: Deploy Prod
      needs: deploy_dev
      uses: ./.github/workflows/steps-deploy.yml
      with:
        env: prod 
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        app_service_name: ${{ env.app_service_name }} 