name: Secrets workflow 

on:
  pull_request: [ "main" ]

env:
  API_CSPROJ_PATH: ContactsManager.Web/ContactsManager.Web.csproj

jobs:
  secrets:
    name: Secrets Demo
    env: 
      JOB_NAME: Secrets
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "Job is $JOB_NAME API path is $API_CSPROJ_PATH"
        
      - name: Repository Secrets
        run: echo "secret key is ${{ secrets.SECRET_TOKEN }}